### ISSUE TITLE
REST API route mist vereist callback argument

### ISSUE THREAD

**Issue by filip-van-hoeckel** [Libertarische-Partij/lightning-checkout-gateway#12]
`PHP Notice:  Functie register_rest_route werd verkeerd aangeroepen. In de REST API route definitie voor lnc-gateway/v1/checkpaymentstatus ontbreekt het vereiste permission_callback argument. Voor REST API routes die bedoeld zijn openbaar te zijn, gebruik __return_true als de toestemming callback. `

**Comment by milovanderlinden** [comment]
In mijn ogen moet op regel 29 van https://github.com/Libertarische-Partij/lightning-checkout-gateway/blob/main/includes/rest.php 'permission_callback' => '__return_true'
